# Generated by Django 5.2.7 on 2026-01-05 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_locationcroatia_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='listing_pictures/', verbose_name='picture')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('used', 'Rabljeno'), ('refurbished', 'Obnovljeno')], default='new', max_length=50, null=True, verbose_name='condition')),
                ('delivery', models.CharField(choices=[('pickup', 'Osobno preuzimanje'), ('shipping', 'Dostava o trošku primatelja')], max_length=50, verbose_name='Delivery options')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='users.locationcroatia')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
