# Generated by Django 5.2.7 on 2025-11-07 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='listing_pictures/', verbose_name='picture')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('payment', models.CharField(max_length=50, verbose_name='payment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
