# Generated by Django 5.2.7 on 2025-11-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='listing_pictures/', verbose_name='picture')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('delivery', models.CharField(max_length=50, verbose_name='payment')),
            ],
        ),
    ]
