# Generated by Django 5.2.7 on 2025-11-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='payment',
            new_name='delivery',
        ),
    ]
