# Generated by Django 5.2.7 on 2025-11-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Novo'), ('used', 'Rabljeno'), ('refurbished', 'Obnovljeno')], default='new', max_length=50, null=True, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='delivery',
            field=models.CharField(choices=[('pickup', 'Osobno preuzimanje'), ('shipping', 'Dostava o trošku primatelja')], max_length=50, verbose_name='Delivery options'),
        ),
    ]
