# Generated by Django 5.2.7 on 2025-11-12 21:58

from django.db import migrations

categories = [
    'Plišanci',
    'Lutke',
    'Autići i vozila',
    'Figurice',
    'Kocke i konstrukcijske igračke',
    'Puzzle i slagalice',
    'Društvene igre',
    'Karte za igranje',
    'Glazbene igračke',
    'Instrumenti',
    'Kreativne igračke',
    'Umjetničke igračke',
    'Modeliranje (plastelin, pijesak)',
    'Edukativne igračke',
    'Elektroničke igračke',
    'Drvene igračke',
    'Magnetne igračke',
    'Igračke za bebe',
    'Senzorne i motoričke igračke',
    'Igračke za van',
    'Sportske igračke',
    'Igre logike i memorije',
    'Kućice i pribor za lutke',
    'Maštovite i kostimske igračke',
    'Tematske igračke',
    'Ekološki prihvatljive igračke',
    'Ostalo'
]

def add_categories(apps, schema_editor):
    category = apps.get_model('listings', 'ProductCategory')
    for name in categories:
        category.objects.create(categoryName=name)

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_productcategory'),
    ]

    operations = [
        migrations.RunPython(add_categories)
    ]
