# Generated by Django 5.2.7 on 2025-11-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_status_listing_condition_and_more'),
        ('users', '0006_load_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='users.locationcroatia'),
        ),
    ]
