# Generated by Django 5.2.7 on 2026-01-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_active_confirmed_donation_conversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active_confirmed_donation_conversation',
            new_name='confirmed_donation_conversation',
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Dostupno'), ('accepted_donation', 'Prihvaćena donacija'), ('payment_requested', 'Zatražena uplata za dostavu'), ('waiting_for_pickup', 'Čeka potvrdu primopredaje'), ('completed', 'Završeno')], default='available', max_length=50, verbose_name='status'),
        ),
    ]
