# Generated by Django 5.2.7 on 2026-01-14 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_load_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_channel_id', models.CharField(max_length=100, unique=True, verbose_name='channel_id')),
                ('delivery_check', models.BooleanField(default=False, verbose_name='delivery_check')),
                ('delivery_chat_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='delivery_chat_id')),
                ('delivery_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery_type')),
                ('delivery_accepted', models.BooleanField(default=False, verbose_name='delivery_accepted')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='delivery_price')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_chats', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='listings.listing')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('donor', 'recipient', 'listing')},
            },
        ),
    ]
