# Generated by Django 5.2.7 on 2026-01-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatchannel',
            name='delivery_chat_id',
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='delivery_request_msg_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Delivery request message ID'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='delivery_accepted',
            field=models.BooleanField(default=False, verbose_name='Delivery accepted'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='delivery_check',
            field=models.BooleanField(default=False, verbose_name='Requested delivery'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Requested delivery type'),
        ),
    ]
