# Generated by Django 5.2.7 on 2026-01-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatchannel_delivery_chat_id_and_more'),
        ('payments', '0006_payment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatchannel',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_channel', to='payments.payment'),
        ),
    ]
