# Generated by Django 5.2.7 on 2026-01-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatchannel_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='payment_request_msg_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Payment request message ID'),
        ),
    ]
