# PlayForward - DigitalOcean App Platform deployment for SANDBOX environment

name: playforward-sandbox
region: fra
envs:
  - key: DJANGO_DEBUG
    value: "true"
    type: GENERAL
    scope: RUN_TIME

services:
  - name: web
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: dgavranic/progitest
      registry_credentials: ${GHCR_CREDENTIALS}
      digest: ${SAMPLE_DIGEST}
    environment_slug: python
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8000
    envs:
      # superuser env
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
        type: GENERAL
        scope: RUN_TIME
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@playforward.com
        type: GENERAL
        scope: RUN_TIME
      - key: DJANGO_SUPERUSER_PASSWORD
        value: ${DJANGO_SUPERUSER_PASSWORD}
        type: SECRET
        scope: RUN_TIME
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
        type: GENERAL
        scope: RUN_TIME
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
        type: SECRET
        scope: RUN_TIME
      - key: DATABASE_URL
        value: ${POSTGRES_DB_URL}
        type: GENERAL
        scope: RUN_TIME
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
        type: GENERAL
        scope: RUN_TIME
      - key: STATIC_ROOT
        value: "/staticfiles"
        type: GENERAL
        scope: RUN_TIME
    health_check:
      http_path: /
      port: 8000
      initial_delay_seconds: 5
      timeout_seconds: 5
