# Generated by Django 5.2.7 on 2025-11-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('recipient_individual', 'Recipient Individual'), ('recipient_association', 'Recipient Association')], max_length=25),
        ),
    ]
