# Generated by Django 5.2.7 on 2025-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_association_delete_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCroatia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
            ],
        ),
    ]
