# Generated by Django 5.2.7 on 2026-01-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcroatia',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
