# Generated by Django 5.2.7 on 2025-11-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_organization_email_user_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_name',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
