# Generated by Django 5.2.7 on 2026-01-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_locationcroatia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
