# Generated by Django 5.2.7 on 2026-01-07 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_locationcroatia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
