# Generated by Django 5.2.7 on 2025-11-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_registration_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_completed',
        ),
        migrations.AddField(
            model_name='user',
            name='registration_step',
            field=models.IntegerField(default=0),
        ),
    ]
