# Generated by Django 5.2.7 on 2025-11-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_organization_email_and_more'),
        ('users', '0009_remove_user_registration_completed_and_more'),
    ]

    operations = [
    ]
