# Generated by Django 5.2.7 on 2025-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20251107_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_update_role', 'Can access update role'), ('can_access_update_type', 'Can access update type'), ('can_access_basic_info', 'Can access basic info'), ('can_access_udruga_additional_info', 'Can access udruga additional info')]},
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Company email'),
        ),
    ]
