# Generated by Django 5.2.7 on 2026-01-09 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_load_categories'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='The listing being delivered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Delivery cost amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='donor',
            field=models.ForeignKey(help_text='The donor receiving the payment for delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received_as_donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(help_text='The recipient paying for the delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made_as_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
