# Generated by Django 5.2.7 on 2026-01-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_listing_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_link_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
