# Generated by Django 5.2.7 on 2026-01-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_stripe_payment_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
    ]
