# Generated by Django 5.2.7 on 2026-01-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_link_url',
            new_name='pay_url',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='stripe_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_account_id',
        ),
    ]
