# Generated by Django 5.2.7 on 2026-01-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_stripe_payment_link_url_payment_pay_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default="Test payment", help_text='Name for the payment', max_length=255),
            preserve_default=False,
        ),
    ]
