import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://sandbox.playforward.dedyn.io/prijava?next=/")
    page.get_by_role("link", name="Registriraj se").click()
    page.get_by_role("textbox", name="E-mail*").click()
    page.get_by_role("textbox", name="E-mail*").fill("testiranjeprogi@gmail.com")
    page.get_by_role("textbox", name="E-mail*").press("Tab")
    page.get_by_role("textbox", name="Lozinka*").fill("sifra1234")
    page.get_by_role("button", name="Stvori novi račun").click()
    page.get_by_role("button", name="Donator").click()
    page.get_by_role("textbox", name="Unesite ime").click()
    page.get_by_role("textbox", name="Unesite ime").fill("Ivan")
    page.get_by_role("textbox", name="Unesite ime").press("Tab")
    page.get_by_role("textbox", name="Unesite prezime").fill("Horvat")
    page.get_by_role("textbox", name="Unesite korisničko ime").click()
    page.get_by_role("textbox", name="Unesite korisničko ime").fill("testiranjeprogi23")
    page.get_by_role("button", name="Show popup").click()
    page.get_by_text("Ivanić-Grad").click()
    page.get_by_role("checkbox", name="Potvrđujem da sam punoljetna").click()
    page.get_by_role("button", name="Registriraj").click()
    page.get_by_role("heading", name="Pozdrav, Ivan! 👋").click()
    page.get_by_role("button", name="Ivan Horvat Ivan Horvat Donor").click()
    page.get_by_role("menuitem", name="Profil").click()
    page.get_by_role("textbox").first.click()
    page.get_by_role("textbox").first.fill("Marko")
    page.locator("uformgroup").filter(has_text="Prezime:").get_by_role("textbox").click()
    page.locator("uformgroup").filter(has_text="Prezime:").get_by_role("textbox").fill("Kovač")
    page.locator("uformgroup").filter(has_text="Korisničko ime:").get_by_role("textbox").click()
    page.locator("uformgroup").filter(has_text="Korisničko ime:").get_by_role("textbox").click()
    page.locator("uformgroup").filter(has_text="Korisničko ime:").get_by_role("textbox").press("ArrowRight")
    page.locator("uformgroup").filter(has_text="Korisničko ime:").get_by_role("textbox").press("ArrowRight")
    page.locator("uformgroup").filter(has_text="Korisničko ime:").get_by_role("textbox").press("ArrowRight")
    page.locator("uformgroup").filter(has_text="Korisničko ime:").get_by_role("textbox").press("ArrowRight")
    page.locator("uformgroup").filter(has_text="Korisničko ime:").get_by_role("textbox").fill("testiranjeprogi2345")
    page.get_by_role("button", name="Show popup").click()
    page.get_by_text("Rab").click()
    page.get_by_role("button", name="Spremi promjene").click()
    page.get_by_role("link", name="Početna").click()
    page.get_by_role("heading", name="Pozdrav, Marko! 👋").click()
    page.get_by_role("button", name="Marko Kovač Marko Kovač Donor").click()
    page.get_by_role("menuitem", name="Odjava").click()
    page.get_by_role("link", name="Idi na prijavu").click()
