import re
from playwright.sync_api import Page, expect

def test_chat(page: Page) -> None:
   page.goto('https://sandbox.playforward.dedyn.io/prijava?next=/')
   page.get_by_role('textbox',  name= 'E-mail*' ).click()
   page.get_by_role('textbox',  name= 'E-mail*' ).fill('testiranjeprogi@gmail.com')
   page.get_by_role('textbox',  name= 'E-mail*' ).press('Tab')
   page.get_by_role('textbox',  name= 'Lozinka*' ).fill('sifra1234')
   page.get_by_role('button',  name= 'Prijava', exact=True ).click()
   page.get_by_role('heading',  name= 'Oglas za testiranje chata' ).click()
   page.get_by_role('button',  name= 'Započni razgovor' ).click()
   page.get_by_role('textbox',  name= 'Napišite poruku...' ).click()
   page.get_by_role('textbox',  name= 'Napišite poruku...' ).fill('Molim Vas za donaciju.')
   page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
   page.get_by_role('button',  name= 'Zahtjev' ).click()
   page.get_by_role('radio',  name= 'Osobno preuzimanje' ).click()
   page.get_by_role('button',  name= 'Pošalji zahtjev' ).click()
   page.get_by_role('button',  name= 'Ivan Horvat Ivan Horvat Udruga' ).click()
   page.get_by_role('menuitem',  name= 'Odjava' ).click()
   page.get_by_role('link', name = 'Idi na prijavu' ).click()
   page.get_by_role('textbox', name = 'E-mail*' ).click()
   page.get_by_role('textbox', name = 'E-mail*' ).fill('test@test.test')
   page.get_by_role('textbox', name = 'E-mail*' ).press('Tab')
   page.get_by_role('textbox', name = 'Lozinka*' ).fill('sifra1234')
   page.get_by_role('button', name = 'Prijava', exact=True ).click()
   page.get_by_role('link', name = 'Moji oglasi' ).click()
   page.get_by_role('link', name = 'Razgovori' ).click()
   page.get_by_role('button', name = 'Oglas za testiranje chata' ).click()
   page.reload()
   page.get_by_role('textbox', name = 'Napišite poruku...' ).click()
   page.get_by_role('textbox', name = 'Napišite poruku...' ).fill('Nema problema! Molim Vas da se nađemo u petak u 11.')
   page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
   page.get_by_role('button', name = 'Prihvati donaciju' ).click()
   page.get_by_text('Molim Vas za donaciju.').click()
   page.get_by_role('button', name = 'Test Testić Test Testić Donor' ).click()
   page.get_by_role('menuitem', name = 'Odjava' ).click()
   page.get_by_role('link', name = 'Idi na prijavu' ).click()
   page.get_by_role('textbox', name = 'E-mail*' ).click()
   page.get_by_role('textbox', name = 'E-mail*' ).fill('testiranjeprogi@gmail.com')
   page.get_by_role('textbox', name = 'E-mail*' ).press('Tab')
   page.get_by_role('textbox', name = 'Lozinka*' ).fill('sifra1234')
   page.get_by_role('button', name = 'Prijava', exact=True ).click()
   page.get_by_role('link', name = 'Razgovori' ).click()
   page.get_by_role('button', name = 'Oglas za testiranje chata' ).click()
   page.reload()
   page.get_by_role('heading', name = 'Donacija prihvaćena' ).click()
   page.get_by_text('Nema problema! Molim Vas da').click()
   page.get_by_role('button', name = 'Ivan Horvat Ivan Horvat Udruga' ).click()
   page.get_by_role('menuitem', name = 'Odjava' ).click()
   page.get_by_role('link', name = 'Idi na prijavu' ).click()