import re
from playwright.sync_api import Page, expect


def test_admin(page: Page) -> None:
    page.goto("https://sandbox.playforward.dedyn.io/prijava?next=/")
    page.get_by_role("textbox", name="E-mail*").click()
    page.get_by_role("link", name="Registriraj se").click()
    page.get_by_role("textbox", name="E-mail*").click()
    page.get_by_role("textbox", name="E-mail*").fill("dz1v4n@gmail.com")
    page.get_by_role("textbox", name="E-mail*").press("Tab")
    page.get_by_role("textbox", name="Lozinka*").fill("sifra1234")
    page.get_by_role("button", name="Stvori novi račun").click()
    page.get_by_role("button", name="Primatelj").click()
    page.get_by_role("button", name="Udruga").click()
    page.get_by_role("textbox", name="Unesite ime").click()
    page.get_by_role("textbox", name="Unesite ime").fill("test")
    page.get_by_role("textbox", name="Unesite prezime").click()
    page.get_by_role("textbox", name="Unesite prezime").fill("test")
    page.get_by_role("textbox", name="Unesite korisničko ime").click()
    page.get_by_role("textbox", name="Unesite korisničko ime").fill("udruga12")
    page.get_by_role("button", name="Show popup").click()
    page.get_by_role("option", name="Dubrovnik").click()
    page.get_by_role("checkbox", name="Potvrđujem da sam punoljetna").click()
    page.get_by_role("button", name="Nastavak ➜").click()
    page.get_by_role("textbox", name="Ime udruge").click()
    page.get_by_role("textbox", name="Ime udruge").fill("ivan.dzepina1407@gmail.com")
    page.get_by_role("textbox", name="Ime udruge").press("Tab")
    page.get_by_role("textbox", name="Email udruge").fill("Mali testi")
    page.get_by_role("textbox", name="Ime udruge").click()
    page.get_by_role("textbox", name="Ime udruge").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Ime udruge").fill("Mali kaktusi")
    page.get_by_role("textbox", name="Email udruge").click()
    page.get_by_role("textbox", name="Email udruge").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Email udruge").fill("ivan.dzepina1407@gmail.com")
    page.get_by_role("button", name="Registriraj").click()
    page.get_by_role("link", name="Moje kampanje").click()
    page.get_by_role("link", name="Nova kampanja").click()
    page.get_by_role("textbox", name="Naslov").click()
    page.get_by_role("textbox", name="Naslov").fill("test kampanja")
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Dodajte ručno ili povucite").click()
    file_chooser = fc_info.value
    file_chooser.set_files("C:\\Users\\Milan\\Desktop\\Progi TESTOVI\\test_slika.jpg")
    page.get_by_role("textbox", name="Opis kampanje").click()
    page.get_by_role("textbox", name="Opis kampanje").fill("test")
    page.get_by_role("button", name="Show popup").click()
    page.get_by_text("Makarska").click()
    page.get_by_role("textbox", name="Datum završetka kampanje").fill("2027-05-05")
    page.get_by_role("textbox", name="Naziv igračke").click()
    page.get_by_role("textbox", name="Naziv igračke").fill("gggggg")
    page.get_by_role("button", name="Dodaj igračku").click()
    page.locator("#v-540").click()
    page.locator("#v-540").fill("asdasadsd")
    page.get_by_role("button", name="Dodaj igračku").click()
    page.locator("#v-541").click()
    page.locator("#v-541").fill("asdasdasd")
    page.get_by_role("button", name="Pregledaj i objavi kampanju").click()
    page.get_by_role("button", name="Objavi").click()
    page.get_by_role("button", name="test test test test Udruga").click()
    page.get_by_role("menuitem", name="Odjava").click()
    page.goto("https://sandbox.playforward.dedyn.io/admin/")
    page.get_by_role("textbox", name="Email address *").click()
    page.get_by_role("textbox", name="Email address *").fill("admin@playforward.dedyn.io")
    page.get_by_role("textbox", name="Password *").click()
    page.get_by_role("textbox", name="Password *").fill("playforward2025")
    page.get_by_role("button", name="Log in arrow_forward").click()
    page.locator("#link-campaigns-campaign").click()
    page.get_by_role("link", name="test kampanja", exact=True).click()
    page.get_by_role("link", name="Delete campaign").click()
    page.get_by_role("button", name="Yes, I’m sure").click()
    page.locator("#link-users-user").click()
    page.get_by_role("link", name="dz1v4n@gmail.com").click()
    page.get_by_role("link", name="Delete user").click()
    page.get_by_role("button", name="Yes, I’m sure").click()
    page.get_by_text("admin@playforward.dedyn.io").first.click()
    page.get_by_role("button", name="Log out logout").click()
