import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://sandbox.playforward.dedyn.io/prijava")
    page.get_by_role("textbox", name="E-mail*").click()
    page.get_by_role("textbox", name="E-mail*").fill("dzivan1407@gmail.com")
    page.get_by_role("textbox", name="E-mail*").press("Tab")
    page.get_by_role("textbox", name="Lozinka*").fill("sifra1234")
    page.get_by_role("button", name="Prijava", exact=True).click()
    page.get_by_role("link", name="Razgovori").click()
    page.get_by_role("button", name="test12 test12 dz1v4n").click()
    page.get_by_role("button", name="Naplati dostavu").click()
    page.get_by_role("spinbutton", name="Iznos dostave (€)").click()
    page.get_by_role("spinbutton", name="Iznos dostave (€)").fill("3")
    page.get_by_role("button", name="Pošalji").click()
    page.get_by_role("button", name="test test test test Donor").click()
    page.get_by_role("menuitem", name="Odjava").click()
    page.get_by_role("link", name="Idi na prijavu").click()
    page.get_by_role("textbox", name="E-mail*").click()
    page.get_by_role("textbox", name="E-mail*").fill("dz1v4n@gmail.com")
    page.get_by_role("textbox", name="E-mail*").press("Tab")
    page.get_by_role("textbox", name="Lozinka*").fill("sifra1234")
    page.get_by_role("button", name="Prijava", exact=True).click()
    page.get_by_role("link", name="Razgovori").click()
    page.get_by_role("button", name="test12 test12 test").click()
    with page.expect_popup() as page2_info:
        page.get_by_role("button", name="Plati").click()
    page2 = page2_info.value
    page2.get_by_role("textbox", name="Email").click()
    page2.get_by_role("textbox", name="Email").fill("test@gmail.com")
    page2.get_by_text("Card").dblclick()
    page2.get_by_role("textbox", name="Card number").fill("4242 4242 4242 4242")
    page2.get_by_text("Card").dblclick()
    page2.get_by_role("textbox", name="Expiration").fill("01 / 29")
    page2.get_by_role("textbox", name="CVC").fill("123")
    page2.get_by_role("textbox", name="Cardholder name").fill("test placanje")
    page2.get_by_test_id("hosted-payment-submit-button").click()
    page2.get_by_text("Thanks for your payment").click()
    page.get_by_role("heading", name="Plaćena dostava").click()
    page.get_by_role("link", name="Aktivne donacije").click()
    page.get_by_role("button", name="Potvrdi primopredaju").nth(1).click()
    page.get_by_role("button", name="Potvrdi primopredaju").click()
    page.get_by_role("button").nth(4).click()
    page.locator("div").filter(has_text=re.compile(r"^Komentar$")).nth(1).click()
    page.get_by_role("textbox", name="Komentar").click()
    page.get_by_role("textbox", name="Komentar").fill("super iskustvo")
    page.get_by_role("button", name="Pošalji recenziju").click()
    page.get_by_role("button", name="test test test test Udruga").click()
    page.get_by_role("menuitem", name="Odjava").click()
    page.get_by_role("link", name="Idi na prijavu").click()
